"""fix reminder created_at

Revision ID: 8874cdf11eae
Revises: a63befac1852
Create Date: 2026-02-24 12:44:47.051152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8874cdf11eae'
down_revision: Union[str, Sequence[str], None] = 'a63befac1852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('reminders', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('reminders', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('reminders', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
